import { StyleSheet, Dimensions } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: "100%",
    height: "100%",
    backgroundColor: "white",
    alignItems: "center",
  },
  ProfilePicBtn: {
    width: 180,
    height: 180,
    marginVertical: "10%",
    borderWidth: 1,
    borderRadius: 90,
    borderColor: "#ddd",
    alignSelf: "center",
    justifyContent: "center",
  },
  InputField: {
    flex: 1,
    backgroundColor: "#ccc",
    width: "100%",
    paddingTop: 5,
    alignItems: "flex-start",
    justifyContent: "flex-start",
  },
  ChangeBtn: {
    width: "100%",
    height: 60,
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
    backgroundColor: "white",
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
  },
  FieldText: {
    fontSize: 18,
    paddingVertical: 6,
    paddingLeft: 10,
  },
  confirmEditBtn: {
    width: "100%",
    height: "100%",
    borderRadius: 10,
    alignSelf: "center",
    justifyContent: "center",
    backgroundColor: "white",
    borderColor: "#ccc",
    borderWidth: 1,
  },
  textInput: {
    width: "90%",
    height: 40,
    left: 10,
    borderWidth: 1,
    borderRadius: 15,
    borderColor: "#ccc",
    paddingHorizontal: 10,
    marginTop: 15,
  },
  confirmContainer: {
    width: 60,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "white",
    marginRight: 10,
  },
  modalView: {
    flexDirection: "column",
    alignItems: "center",
    width: "90%",
    height: "40%",
    backgroundColor: "white",
    borderRadius: 10,
    padding: 5,
  },
  btnArea: {
    flex: 1,
    width: "100%",
    height: "50%",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "flex-end",
  },
  modalButton: {
    width: "45%",
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#ccc",
    borderRadius: 10,
    marginHorizontal: 5,
  },
});

export default styles;
