import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "column",
    backgroundColor: "#fff",
    alignItems: "center",
  },
  headerContainer: {
    width: "100%",
    height: "10%",
    justifyContent: "flex-start",
    alignItems: "flex-end",
    flexDirection: "row",
    paddingHorizontal: 20,
    paddingBottom: 10,
  },
  contentContainer: {
    width: "100%",
    height: "80%",
  },
  cafeInfoHeader: {
    width: "100%",
    height: 120,
    justifyContent: "center",
    alignItems: "flex-start",
    backgroundColor: "white",
    flexDirection: "row",
  },
  cafeImagePicker: {
    height: 100,
    width: 100,
    margin: 10,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 15,
  },
  nameInputContainer: {
    width: "70%",
    height: 120,
    padding: 10,
    justifyContent: "center",
    alignItems: "flex-start",
  },
  nameTextInput: {
    backgroundColor: "white",
    width: "100%",
    height: 45,
    borderColor: "#ccc",
    borderBottomWidth: 1,
    marginBottom: 10,
  },
  locationButton: {
    width: "100%",
    height: 45,
    backgroundColor: "#ccc",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 15,
  },
  cafeTimeContainer: {
    width: "100%",
    height: "18%",
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  oncTimeContainer: {
    width: "30%",
    height: "100%",
  },
  timeTextInput: {
    backgroundColor: "white",
    textAlign: "center",
    width: "100%",
    height: 45,
    borderColor: "#ccc",
    borderBottomWidth: 1,
  },
  seatImagePickerContainer: {
    width: "100%",
    height: "58%",
    justifyContent: "center",
    alignItems: "center",
  },
  setImagePicker: {
    width: "95%",
    height: "95%",
    backgroundColor: "white",
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 15,
  },
  submitBtnContainer: {
    width: "100%",
    height: "10%",
    justifyContent: "center",
    alignItems: "center",
  },
  submitButton: {
    width: "95%",
    height: "80%",
    backgroundColor: "#001D44",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 15,
  },
});

export default styles;
