import 'dotenv/config';

export default ({ config }) => ({
  ...config,
  extra: {
    REACT_APP_API_URL: process.env.REACT_APP_API_URL,
    REACT_APP_FIREBASE_API_KEY: process.env.REACT_APP_FIREBASE_API_KEY,
    REACT_APP_FIREBASE_DOMAIN: process.env.REACT_APP_FIREBASE_DOMAIN,
    REACT_APP_FIREBASE_PROJECT: process.env.REACT_APP_FIREBASE_PROJECT,
    REACT_APP_FIREBASE_STOTAGE_BUCKET: process.env.REACT_APP_FIREBASE_STOTAGE_BUCKET,
    REACT_APP_FIREBASE_MSG_SENDER: process.env.REACT_APP_FIREBASE_MSG_SENDER,
    REACT_APP_FIREBASE_API_ID: process.env.REACT_APP_FIREBASE_API_ID,
    REACT_APP_FIREBASE_MEASUREMENTID: process.env.REACT_APP_FIREBASE_MEASUREMENTID,
  },
});